site_name: Catwork
repo_url: https://github.com/metatablecatgames/catwork
repo_name: metatablecatgames/catwork

theme:
  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: PT Sans
    code: Comic Mono

  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate


  name: material

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://tech.lgbt/@metatablecat

extra_css:
  - stylesheet/extra.css

nav:
  - Home: index.md
  - Reference: 
    - reference/index.md
    - Catwork:
      - reference/catwork/index.md
      - Fragment: reference/catwork/fragment.md
      - Service: reference/catwork/service.md
      - Template: reference/catwork/template.md
    - Errors: reference/errors.md


markdown_extensions:
  - admonition
  - attr_list
  - meta
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg