[package]
name = "metatablecat/catwork"
description = "A tiny Service/Fragment based framework"
version = "0.5.0"
license = "MIT"
authors = ["Tami Crouch"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json", "LICENSE"]

[dependencies]
